arb-dir: lib/core/localization/arb
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-class: AppL10n
output-dir: lib/core/localization/generated
nullable-getter: false
